-- Harden community request writes by routing them through trusted RPCs with
-- database-side rate limiting. Client-side throttles remain only as UX hints.

CREATE TABLE IF NOT EXISTS public.community_rate_limits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  action text NOT NULL CHECK (action IN ('create_request', 'submit_reply', 'vote_reply')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_community_rate_limits_user_action_created_at
  ON public.community_rate_limits(user_id, action, created_at DESC);

ALTER TABLE public.community_rate_limits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "community_rate_limits_no_direct_select" ON public.community_rate_limits;
DROP POLICY IF EXISTS "community_rate_limits_no_direct_insert" ON public.community_rate_limits;
DROP POLICY IF EXISTS "community_rate_limits_no_direct_update" ON public.community_rate_limits;
DROP POLICY IF EXISTS "community_rate_limits_no_direct_delete" ON public.community_rate_limits;

CREATE POLICY "community_rate_limits_no_direct_select"
ON public.community_rate_limits FOR SELECT
USING (false);

CREATE POLICY "community_rate_limits_no_direct_insert"
ON public.community_rate_limits FOR INSERT
WITH CHECK (false);

CREATE POLICY "community_rate_limits_no_direct_update"
ON public.community_rate_limits FOR UPDATE
USING (false)
WITH CHECK (false);

CREATE POLICY "community_rate_limits_no_direct_delete"
ON public.community_rate_limits FOR DELETE
USING (false);

CREATE OR REPLACE FUNCTION public.enforce_community_rate_limit(
  p_action text,
  p_max_count integer,
  p_window_seconds integer
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  requester_id uuid := auth.uid();
  current_count integer := 0;
BEGIN
  IF requester_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF p_max_count < 1 OR p_window_seconds < 1 THEN
    RAISE EXCEPTION 'Invalid rate limit configuration';
  END IF;

  DELETE FROM public.community_rate_limits
  WHERE created_at < now() - interval '1 day';

  SELECT count(*)
  INTO current_count
  FROM public.community_rate_limits
  WHERE user_id = requester_id
    AND action = p_action
    AND created_at >= now() - make_interval(secs => p_window_seconds);

  IF current_count >= p_max_count THEN
    RAISE EXCEPTION 'Please wait before trying again.';
  END IF;

  INSERT INTO public.community_rate_limits (user_id, action)
  VALUES (requester_id, p_action);
END;
$$;

CREATE OR REPLACE FUNCTION public.create_movie_request_secure(
  p_tmdb_id text,
  p_media_type text,
  p_title text,
  p_poster_path text DEFAULT NULL
)
RETURNS TABLE (
  id uuid,
  tmdb_id text,
  media_type text,
  title text,
  poster_path text,
  status text,
  created_by uuid,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  requester_id uuid := auth.uid();
  safe_tmdb_id text := NULLIF(btrim(COALESCE(p_tmdb_id, '')), '');
  safe_media_type text := NULLIF(btrim(COALESCE(p_media_type, '')), '');
  safe_title text := NULLIF(btrim(COALESCE(p_title, '')), '');
  safe_poster_path text := NULLIF(btrim(COALESCE(p_poster_path, '')), '');
BEGIN
  IF requester_id IS NULL THEN
    RAISE EXCEPTION 'Must be logged in to request';
  END IF;

  IF safe_tmdb_id IS NULL OR safe_title IS NULL THEN
    RAISE EXCEPTION 'A title and TMDB id are required';
  END IF;

  IF safe_media_type NOT IN ('movie', 'tv') THEN
    RAISE EXCEPTION 'Invalid media type';
  END IF;

  IF length(safe_title) > 250 THEN
    RAISE EXCEPTION 'Title is too long';
  END IF;

  PERFORM public.enforce_community_rate_limit('create_request', 2, 300);

  RETURN QUERY
  INSERT INTO public.movie_requests (
    tmdb_id,
    media_type,
    title,
    poster_path,
    created_by
  )
  VALUES (
    safe_tmdb_id,
    safe_media_type,
    safe_title,
    safe_poster_path,
    requester_id
  )
  RETURNING
    movie_requests.id,
    movie_requests.tmdb_id,
    movie_requests.media_type,
    movie_requests.title,
    movie_requests.poster_path,
    movie_requests.status,
    movie_requests.created_by,
    movie_requests.created_at,
    movie_requests.updated_at;
EXCEPTION
  WHEN unique_violation THEN
    RAISE EXCEPTION 'This movie has already been requested!';
END;
$$;

CREATE OR REPLACE FUNCTION public.submit_request_reply_secure(
  p_request_id uuid,
  p_tmdb_id text,
  p_content text,
  p_instructions text DEFAULT NULL
)
RETURNS TABLE (
  id uuid,
  request_id uuid,
  tmdb_id text,
  content text,
  link_type text,
  instructions text,
  upvotes integer,
  created_by uuid,
  created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  requester_id uuid := auth.uid();
  safe_tmdb_id text := NULLIF(btrim(COALESCE(p_tmdb_id, '')), '');
  safe_content text := NULLIF(btrim(COALESCE(p_content, '')), '');
  safe_instructions text := NULLIF(btrim(COALESCE(p_instructions, '')), '');
  resolved_link_type text;
BEGIN
  IF requester_id IS NULL THEN
    RAISE EXCEPTION 'Must be logged in to reply';
  END IF;

  IF p_request_id IS NULL OR safe_tmdb_id IS NULL OR safe_content IS NULL THEN
    RAISE EXCEPTION 'A request id, TMDB id, and link are required';
  END IF;

  IF safe_content !~* '^(magnet:|https?://)' THEN
    RAISE EXCEPTION 'Invalid link format. Must be a URL or magnet link.';
  END IF;

  IF length(safe_content) > 2000 THEN
    RAISE EXCEPTION 'Link is too long (max 2000 characters).';
  END IF;

  IF safe_instructions IS NOT NULL AND length(safe_instructions) > 500 THEN
    RAISE EXCEPTION 'Instructions are too long (max 500 characters).';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.movie_requests
    WHERE id = p_request_id
      AND tmdb_id = safe_tmdb_id
  ) THEN
    RAISE EXCEPTION 'Request not found';
  END IF;

  resolved_link_type := CASE
    WHEN safe_content ~* '^magnet:' THEN 'magnet'
    WHEN safe_content ~* 'drive\.google\.com' THEN 'gdrive'
    WHEN safe_content ~* 'mega\.nz' THEN 'mega'
    WHEN safe_content ~* '(youtube\.com|vimeo|\.m3u8)' THEN 'stream'
    ELSE 'other'
  END;

  PERFORM public.enforce_community_rate_limit('submit_reply', 3, 180);

  UPDATE public.movie_requests
  SET status = 'fulfilled', updated_at = now()
  WHERE id = p_request_id;

  RETURN QUERY
  INSERT INTO public.request_replies (
    request_id,
    tmdb_id,
    content,
    link_type,
    instructions,
    created_by
  )
  VALUES (
    p_request_id,
    safe_tmdb_id,
    safe_content,
    resolved_link_type,
    safe_instructions,
    requester_id
  )
  RETURNING
    request_replies.id,
    request_replies.request_id,
    request_replies.tmdb_id,
    request_replies.content,
    request_replies.link_type,
    request_replies.instructions,
    request_replies.upvotes,
    request_replies.created_by,
    request_replies.created_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_reply_vote(
  p_reply_id uuid,
  p_vote integer
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_vote integer;
  new_total integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF p_vote NOT IN (1, -1) THEN
    RAISE EXCEPTION 'Invalid vote';
  END IF;

  PERFORM public.enforce_community_rate_limit('vote_reply', 10, 60);

  SELECT vote INTO current_vote
  FROM public.reply_votes
  WHERE reply_id = p_reply_id AND user_id = auth.uid();

  IF current_vote IS NOT NULL THEN
    IF current_vote = p_vote THEN
      RETURN (SELECT upvotes FROM public.request_replies WHERE id = p_reply_id);
    END IF;

    UPDATE public.reply_votes
    SET vote = p_vote
    WHERE reply_id = p_reply_id AND user_id = auth.uid();

    UPDATE public.request_replies
    SET upvotes = upvotes + (p_vote - current_vote)
    WHERE id = p_reply_id
    RETURNING upvotes INTO new_total;
  ELSE
    INSERT INTO public.reply_votes (reply_id, user_id, vote)
    VALUES (p_reply_id, auth.uid(), p_vote);

    UPDATE public.request_replies
    SET upvotes = upvotes + p_vote
    WHERE id = p_reply_id
    RETURNING upvotes INTO new_total;
  END IF;

  RETURN new_total;
END;
$$;

DROP POLICY IF EXISTS "Users can create requests" ON public.movie_requests;
DROP POLICY IF EXISTS "movie_requests_block_direct_insert" ON public.movie_requests;
CREATE POLICY "movie_requests_block_direct_insert"
ON public.movie_requests FOR INSERT
WITH CHECK (false);

DROP POLICY IF EXISTS "Users can add replies" ON public.request_replies;
DROP POLICY IF EXISTS "request_replies_block_direct_insert" ON public.request_replies;
CREATE POLICY "request_replies_block_direct_insert"
ON public.request_replies FOR INSERT
WITH CHECK (false);

DROP POLICY IF EXISTS "Users can vote" ON public.reply_votes;
DROP POLICY IF EXISTS "Users can change their vote" ON public.reply_votes;
DROP POLICY IF EXISTS "reply_votes_block_direct_insert" ON public.reply_votes;
DROP POLICY IF EXISTS "reply_votes_block_direct_update" ON public.reply_votes;

CREATE POLICY "reply_votes_block_direct_insert"
ON public.reply_votes FOR INSERT
WITH CHECK (false);

CREATE POLICY "reply_votes_block_direct_update"
ON public.reply_votes FOR UPDATE
USING (false)
WITH CHECK (false);

REVOKE ALL ON FUNCTION public.enforce_community_rate_limit(text, integer, integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.enforce_community_rate_limit(text, integer, integer) TO service_role;

REVOKE ALL ON FUNCTION public.create_movie_request_secure(text, text, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_movie_request_secure(text, text, text, text) TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.submit_request_reply_secure(uuid, text, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_request_reply_secure(uuid, text, text, text) TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.handle_reply_vote(uuid, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.handle_reply_vote(uuid, integer) TO authenticated, service_role;
